name: Continuous Delivery Conferences and Events
highlighter: rouge
exclude: [README.md]
timezone: Europe/Copenhagen
url: new.code-conf.com
markdown: kramdown

collections:
  events:
    output: true
    permalink: /:path/
    #permalink: /training/:path/
  speakers:
    output: true

defaults:
 -
    scope:
      type: events
    values:
      layout: event
