# Only use gems that are supported by github
# the gems must be installed on your local system to support jekyll build/serve
# Example
#    $ gem install jekyll-redirect-from
gems:
  - jekyll-redirect-from

name: Continuous Delivery Conferences and Events
email: info@praqma.com
email_sponsor_inquires: ah@praqma.net
highlighter: rouge
exclude: [README.md]
timezone: Europe/Copenhagen
url: new.code-conf.com
markdown: kramdown

page_color: black;

event_types:
  - all: All events
  - conferences: Conferences
  - meet-ups: Meet-ups
  - hackathons: Hackathons
filter_event:
  filter_any_item_tag: all
  event_page_url: /events/
  event_page_css_selector: .page-events
  event_page_all_events_header: "All events"
filter_speaker:
  filter_any_item_tag: all
  page_url: /speakers/
  page_css_selector: .page-speakers
  all_header: "All events"

social:
  twitter:
    https://twitter.com/praqma
  linkedin:
    https://www.linkedin.com/company/praqma-a-s
  google_plus:
    https://plus.google.com/100636273457335734278/videos

footer:
  - Brought to you by the folks at
  - /images/praqmalogo.png
  - The Continuous Delivery and DevOps Company
praqma:
  url: http://praqma.com

collections:
  events:
    output: true
    permalink: /:path/
    #permalink: /training/:path/
  speakers:
    output: true
  sponsors:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
  -
    scope:
      type: events
    values:
      layout: event
      weight: 9999999
